// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIC_XekwpYBR8oA5z09IlacEXxtCvn1c',
    appId: '1:273275159796:web:4274bb49830bf037370aa1',
    messagingSenderId: '273275159796',
    projectId: 'testingproject-db7ee',
    authDomain: 'testingproject-db7ee.firebaseapp.com',
    storageBucket: 'testingproject-db7ee.firebasestorage.app',
    measurementId: 'G-XTD8EDQG8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8zfcQVVKyYRMylUuWnI61bsEOwb65hT4',
    appId: '1:273275159796:android:5bf4f7d6bfb13720370aa1',
    messagingSenderId: '273275159796',
    projectId: 'testingproject-db7ee',
    storageBucket: 'testingproject-db7ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfYgLbKAjOf9wLTPYf1542PKW41hy0jc',
    appId: '1:273275159796:ios:a6a7419c7368c187370aa1',
    messagingSenderId: '273275159796',
    projectId: 'testingproject-db7ee',
    storageBucket: 'testingproject-db7ee.firebasestorage.app',
    iosBundleId: 'com.example.fluttertutorials',
  );
}
